name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run pelican
